name: mobile
description: Flutter mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: ^3.41.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  firebase_core: ^4.4.0
  firebase_crashlytics: ^5.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  forui: ^0.19.0
  freezed_annotation: ^3.0.0
  get_it: ^9.2.1
  go_router: ^17.1.0
  injectable: ^2.6.0
  intl: any
  jiffy: ^6.3.2
  json_annotation: ^4.11.0
  retrofit: ^4.5.0
  riverpod_annotation: ^4.0.2

dev_dependencies:
  build_runner: ^2.11.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.5
  injectable_generator: ^2.12.0
  json_serializable: ^6.13.0
  mocktail: ^1.0.4
  retrofit_generator: ^10.2.3
  riverpod_generator: ^4.0.3
  swagger_parser: ^1.42.0
  very_good_analysis: ^10.2.0

flutter:
  generate: true
  uses-material-design: true
